### ISSUE TITLE
SSLError in lastfm_downloader / fixes for python3

### ISSUE THREAD

**Issue by pussinboot** [gboeing/data-visualization#1]
If you get this error
`SSLError: [SSL: CERTIFICATE_VERIFY_FAILED]`
Then change 
`response = requests.get(request_url).json()`
to
`response = requests.get(request_url,verify=False).json()`
wherever you see requests.get

**Comment by pussinboot** [comment]
this is an issue you may encounter if you're trying to run the script with python 3, there's a couple more fixes you need to make that have to do with printing

**Comment by pussinboot** [comment]
AttributeError: 'DataFrame' object has no attribute 'sort_values'
if you get this error you need to update pandas : )

**Comment by gboeing** [comment]
Thanks, I have just updated all the Python code for Python 3.5 compatibility.
