### ISSUE TITLE
Wikipedia population graph out of date

### ISSUE THREAD

**Issue by AgnerF** [gboeing/data-visualization#2]
The graphs on Wikipedia are out of date. https://en.wikipedia.org/wiki/Projections_of_population_growth
I need an up-to-date version of the "estimates of population levels in different continents" graph for a new book (log scale). I would be very grateful if you could update this graph https://en.wikipedia.org/wiki/Projections_of_population_growth#/media/File:World_population_(UN).svg

**Comment by gboeing** [comment]
This isn't an issue with the repo, so I'm closing this here. But if you'd like to reach out to me regarding this project you can do so at http://geoffboeing.com/contact/
